### ISSUE TITLE
python build shows errors

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#508]
In a clean virtual environment, Linux Ubuntu 20, Python 3.9, I get (non-fatal) errors building & installing tiledbpython (`main` branch). 

```
   command: /home/bruce/test_notebooks/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxnt9l__/umap-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxnt9l__/umap-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6r8qjabx
       cwd: /tmp/pip-install-qxnt9l__/umap-learn/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  ```

Full example:
```
$ python -m venv ./venv
$ source ./venv/bin/activate
(venv) $ pip list
Package       Version
------------- -------
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    44.0.0 
$ pip --version
pip 20.0.2 from /home/bruce/test_notebooks/venv/lib/python3.9/site-packages/pip (python 3.9)
$ cd TileDB-SOMA/apis/python
(venv) $ pip install -e .
Obtaining file:///home/bruce/test_notebooks/TileDB-SOMA/apis/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting anndata
  Using cached anndata-0.8.0-py3-none-any.whl (96 kB)
Collecting scanpy
  Using cached scanpy-1.9.1-py3-none-any.whl (2.0 MB)
Collecting tiledb>=0.18.1
  Using cached tiledb-0.18.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
Collecting scipy
  Using cached scipy-1.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
Collecting pandas
  Using cached pandas-1.5.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Collecting pyarrow
  Using cached pyarrow-10.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.2 MB)
Collecting packaging>=20
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting h5py>=3
  Using cached h5py-3.7.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
Collecting natsort
  Using cached natsort-8.2.0-py3-none-any.whl (37 kB)
Collecting numpy>=1.16.5
  Using cached numpy-1.23.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting numba>=0.41.0
  Downloading numba-0.56.4-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 4.8 MB/s 
Collecting scikit-learn>=0.22
  Using cached scikit_learn-1.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.8 MB)
Collecting umap-learn>=0.3.10
  Using cached umap-learn-0.5.3.tar.gz (88 kB)
Collecting joblib
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting session-info
  Using cached session_info-1.0.0.tar.gz (24 kB)
Collecting seaborn
  Using cached seaborn-0.12.1-py3-none-any.whl (288 kB)
Collecting patsy
  Using cached patsy-0.5.3-py2.py3-none-any.whl (233 kB)
Collecting networkx>=2.3
  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)
Collecting matplotlib>=3.4
  Using cached matplotlib-3.6.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
Collecting statsmodels>=0.10.0rc2
  Using cached statsmodels-0.13.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1
  Using cached pytz-2022.6-py2.py3-none-any.whl (498 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting llvmlite<0.40,>=0.39.0dev0
  Using cached llvmlite-0.39.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
Requirement already satisfied: setuptools in /home/bruce/test_notebooks/venv/lib/python3.9/site-packages (from numba>=0.41.0->scanpy->tiledbsoma==0.5.0a2.dev99) (44.0.0)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting pynndescent>=0.5
  Using cached pynndescent-0.5.8.tar.gz (1.1 MB)
Collecting stdlib_list
  Using cached stdlib_list-0.8.0-py3-none-any.whl (63 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-9.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.0.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (296 kB)
Building wheels for collected packages: umap-learn, session-info, pynndescent
  Building wheel for umap-learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bruce/test_notebooks/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxnt9l__/umap-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxnt9l__/umap-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6r8qjabx
       cwd: /tmp/pip-install-qxnt9l__/umap-learn/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for umap-learn
  Running setup.py clean for umap-learn
  Building wheel for session-info (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bruce/test_notebooks/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxnt9l__/session-info/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxnt9l__/session-info/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h7i4e8mf
       cwd: /tmp/pip-install-qxnt9l__/session-info/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for session-info
  Running setup.py clean for session-info
  Building wheel for pynndescent (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bruce/test_notebooks/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxnt9l__/pynndescent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxnt9l__/pynndescent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6dkrazjm
       cwd: /tmp/pip-install-qxnt9l__/pynndescent/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pynndescent
  Running setup.py clean for pynndescent
Failed to build umap-learn session-info pynndescent
Installing collected packages: numpy, scipy, pyparsing, packaging, six, python-dateutil, pytz, pandas, h5py, natsort, anndata, tqdm, llvmlite, numba, threadpoolctl, joblib, scikit-learn, pynndescent, umap-learn, stdlib-list, session-info, fonttools, pillow, kiwisolver, cycler, contourpy, matplotlib, seaborn, patsy, networkx, statsmodels, scanpy, tiledb, pyarrow, tiledbsoma
    Running setup.py install for pynndescent ... done
    Running setup.py install for umap-learn ... done
    Running setup.py install for session-info ... done
  Running setup.py develop for tiledbsoma
Successfully installed anndata-0.8.0 contourpy-1.0.6 cycler-0.11.0 fonttools-4.38.0 h5py-3.7.0 joblib-1.2.0 kiwisolver-1.4.4 llvmlite-0.39.1 matplotlib-3.6.2 natsort-8.2.0 networkx-2.8.8 numba-0.56.4 numpy-1.23.4 packaging-21.3 pandas-1.5.1 patsy-0.5.3 pillow-9.3.0 pyarrow-10.0.0 pynndescent-0.5.8 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.6 scanpy-1.9.1 scikit-learn-1.1.3 scipy-1.9.3 seaborn-0.12.1 session-info-1.0.0 six-1.16.0 statsmodels-0.13.5 stdlib-list-0.8.0 threadpoolctl-3.1.0 tiledb-0.18.1 tiledbsoma tqdm-4.64.1 umap-learn-0.5.3

```

**Comment by johnkerl** [comment]
@bkmartinjr is this resolved in light of recent build-system upates?

**Comment by bkmartinjr** [comment]
Not fixed on this config - I get exactly the same error.  On other similar configs (eg, Py 3.10, Ubuntu 22) it works fine.  Reproducing requires the clean virtual environment , etc.

Given that this is non-fatal, and likely caused by something upstream of our build process, I suggest treating as low priority for a while.

**Comment by bkmartinjr** [comment]
this seems to have resolved itself at some point.  closing.
